### ISSUE TITLE
How do this work?

### ISSUE THREAD

**Issue by abdulkhafizov07** [knyghty/django-device-cookies#1]
Do this use cookies to store data?

**Comment by knyghty** [comment]
You can find information on how it works at https://owasp.org/www-community/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies

Essentially when you successfully log in with a device a cookie is set. When future logins are made, if this cookie is set, the device used is considered trusted and won't be blocked after multiple incorrect login attempts are made.
